catalyst:
  platform: 'cisco_ios'
  username: 'cisco'
  password: 'cisco'
  connection_options:
    netmiko:
      extras:
        device_type: 'cisco_ios_ssh'
#nexus:
#  platform: 'cisco_nxos'
#  username: 'admin'
#  password: 'Flvby123'
#  connection_options:
#    netmiko:
#      extras:
#        device_type: 'cisco_nxos'